### ISSUE TITLE
Question about wiring to connect to the bus

### ISSUE THREAD

**Issue by Molodos** [Bambu-Research-Group/Bambu-Bus#2]
Hi!

First of all thanks for sharing your research findings in this repo!
I am currently searching for information on how the Bambu Bus works because I want to do some more experiments with it. For that, I somehow need to connect to the bus to be able to intercept the connection. Can you tell me how one would do that?
Can I just use some kind of USB to UART converter and PUTTY? And are there any things to keep in mind (like communication voltages above 5V that could damage my PC)?

Thanks in advance! I love your awesome work :D

**Comment by leonllrmc** [comment]
You can either connect to the bus with a RS485 converter or, 
You can solder wire to the uart pins of the internal RS485 converter from the printer or AMS motherboard

There shouldn't be any problem except if your converter cannot support the about 1Mbit baudrate,
The RS485 should be supplied with 3.3V

**Comment by leonllrmc** [comment]
Also note that there are some existing communications logs avaible, you should be able to find them in the X1plus discord server

**Comment by Molodos** [comment]
Thank you very much for the info, this is exactly what I needed to know! I just ordered a RS485 and am looking forward to experimenting with it. I will also have a look in the X1plus discord, thanks for letting me know!

Have a great day!
